steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- ADICIONE ESTES PASSOS AQUI ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Se o teste falhar aqui, o GitHub para tudo e fica VERMELHO!
      # ----------------------------------

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'